services:
  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - frontend-tier
    environment:
      API_BASE_URL: http://backend:8080

  backend:
    build: ./backend/
    networks:
      - frontend-tier
    ports:
      - 8080:8080

networks:
  frontend-tier:
